function getCity() {
    const cities = [  "San Luis Rio Colorado, Sonora",
    "Ensenada",
    "Veracruz",
    "Merida",
    "Cuernavaca",
    "Guadalajara",
    "Monterrey",
    "Tamaulipas",
    "San Luis Potosi",
    "Ciudad de México",
    "Tijuana",
    "Puebla",
    "Chihuahua",
    "Hermosillo",
    "Durango",
    "Zacatecas",
    "Aguascalientes",
    "Acapulco",
    "Cancun",
    "Boston",
    "Nashville",
    "New York",
    "Detroit",
    "Memphis",
    "Portland",
    "Oklahoma City",
    "Las Vegas",
    "Louisville",
    "Baltimore",
    "Milwaukee",
    "Albuquerque",
    "Tucson",
    "Fresno",
    "Sacramento",
    "Miami",
    "Atlanta",
    "Kansas City",
    "Colorado Springs",
    "Miami",
    "Raleigh",
    "Omaha",
    "Long Beach",
    "Virginia Beach",
    "Oakland",
    "Minneapolis",
    "Tulsa",
    "New Orleans",
    "Arlington",
    "Tampa",
    "Aurora",
    "Santa Ana",
    "St. Louis",
    "Pittsburgh",
    "Corpus Christi",
    "Riverside",
    "Cincinnati",
    "Lexington",
    "Anchorage",
    "Stockton",
    "Toledo",
    "St. Paul",
    "Newark",
    "Greensboro",
    "Buffalo",
    "Plano",
    "Lincoln",
    "Henderson",
    "Fort Wayne",
    "Jersey City",
    "St. Petersburg",
    "Alemania",
    "Norfolk",
    "Orlando",
    "Chandler",
    "Laredo",
    "Madison",
    "Winston-Salem",
    "Lubbock",
    "Baton Rouge",
    "Durham",
    "Garland",
    "Glendale",
    "Reno",
    "Hialeah",
    "Chesapeake",
    "Scottsdale",
    "North Las Vegas",
    "Irving",
    "Fremont",
    "Irvine",
    "Birmingham",
    "Rochester",
    "San Bernardino",
    "Spokane",
    "Gilbert",
    "Arlington",
    "Montgomery",
    "Boise",
    "Richmond",
    "Des Moines",
    "Modesto",
    "Fayetteville",
    "Shreveport",
    "Akron",
    "Tacoma",
    "Aurora",
    "Oxnard",
    "Fontana",
    "Yonkers",
    "Augusta",
    "Mobile",
    "Little Rock",
    "Moreno Valley",
    "Glendale",
    "Huntington Beach",
    "Columbus",
    "Grand Rapids",
    "Salt Lake City",
    "Worcester",
    "Newport News",
    "Huntsville",
    "Tlaxcala",
    "Tampico",
    "Querétaro",
    "Puerto Peñasco",
    "Nogales",
    "Navojoa",
    "Morelia"];
    return cities[Math.floor(Math.random() * cities.length)];
  }
  
  export { getCity };